### ISSUE TITLE
Breaking 4.0.0 changes

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1705]
This is a list of proposed breaking changes for the 4.0.0 release. **Feedback welcome!**

**C# 9 (Visual Studio 16.8) is now required to compile from source**
**[Nullable reference types](https://docs.microsoft.com/dotnet/csharp/nullable-references) are enabled **

Feel free to comment with any breaking changes you would like to request.

- [x] Rename `MaterialDesignFilledPasswordFieldPasswordBox` to `MaterialDesignFilledPasswordBox` #2074 
- [x] Rename `MaterialDesignOutlinedPasswordFieldPasswordBox` to `MaterialDesignOutlinedPasswordBox` #2075
- [x] Rename `MaterialDesignFilledTextFieldTextBox` to `MaterialDesignFilledTextBox` #2076
- [x] Rename `MaterialDesignOutlinedTextFieldTextBox` to `MaterialDesignOutlinedTextBox`  #2078
- [x] Change the default value of `HintAssist.FloatingOffset` to be `(0, -16)` rather than `(1, -16)`
- [x] Change the default `PopupBox.PopupMode` from `MouseOverEager` to `Click`
- [x] Remove the obsolete `DialogClosingEventArgs` constructor. #2079
- [x] Rename `ValidationErrorColor` to be `MaterialDesignValidationErrorColor` #2082
- [x] Change default behavior of `DialogHost.DialogTheme` to be `Inherit`
- [x] Remove `Icon` and `IconType` in favor of `PackIcon` and `PackIconKind` #2079
- [x] Rename `MaterialDesignColors.ColorManipulation.ColorHelper` to `ColorAssist` #2083
- [x] Remove obsolete `LargeArcConverter` #2079
- [x] Remove obsolete Expander Styles #2079
- [x] Remove obsolete `ExpanderAssist` members #2079
- [x] Move `TransitionAssist` to root namespace #2081
- [x] Remove `SecondaryAccentBrush` and `SecondaryAccentBrushColor` #2080
- [x] Remove `SecondaryAccentForegroundBrush` and `SecondaryAccentForegroundBrushColor` #2080

**Comment by DrCQ** [comment]
Vote for:
 Rename ValidationErrorColor to be MaterialDesignValidationErrorColor
Change default behavior of DialogHost.DialogTheme to be Inherit
Remove Icon and IconType in favor of PackIcon and PackIconKind
Rename MaterialDesignColors.ColorManipulation.ColorHelper to ColorAssist

**Comment by timunie** [comment]
Hi @Keboo ,
I really like the new way the Resources are named in MahApps. It was quite a lot of work to get this done, but for the user it is much easier to remember the Keys IMO.

More info: https://mahapps.com/docs/guides/migration-to-v2.0#resource-keys

Just a suggestion, not a must have :-) . 

Happy coding, 
Tim

**Comment by Keboo** [comment]
@timunie yea I have been following the MahApp theming changes and want to take a look at structuring it in a similar manner.

**Comment by jizc** [comment]
I think we should consider removing text field styles that only has an underline, with no fill or outline, i.e. `MaterialDesignTextBox`.

The reasoning for this is that they are no longer part of the spec. They were removed because research, conducted by Google, showed that users had trouble understanding that the line is an input field. It was often confused for a divider, and hint/label text was thought to be body text.

Here is a link to the article about the research:
https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03

If people still want to keep the styles, I think we should at least change the defaults to filled.

**Comment by Keboo** [comment]
@jizc I agree. I think the default should be changed to be the filled. There are not specific styles for the "not filled" (default) TextBox style that exists right now, since it is largely implemented with an attached property (`TextFieldAssist.HasFilledTextField`).
I think simply changing the default to be filled, but leave the attached property in place so if people really want the old look they can opt back into it by changing the attached property.

**Comment by philpowers** [comment]
One thing that I ran into when I upgraded from 3.1 to 4.0 that was not listed here is the changing of the 'ColorModeZone' enum.

It looks like 'Accent' colors are now referred to as 'Secondary' - and cases where I had a <ColorZone Mode="Accent"> I had to change to Mode="SecondaryMid"

Just writing here in case it helps someone in the future.

**Comment by jcummings2** [comment]
> One thing that I ran into when I upgraded from 3.1 to 4.0 that was not listed here is the changing of the 'ColorModeZone' enum.
> 
> It looks like 'Accent' colors are now referred to as 'Secondary' - and specifically in cases where I had a ColorZone with Mode="Accent", I had to change to use Mode="SecondaryMid" instead.
> 
> Just writing here in case it helps someone in the future.

Thank you! It helped me fix a `System.Windows.Markup.XamlParseException` with message,  "'Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.' Line number '138' and line position '17'" and
and `InnerException` of "Accent is not a valid value for ColorZoneMode." The line number an position in question referred to a line like: `materialDesign:ColorZoneAssist.Mode="Accent"` in a `GroupBox`.
